import sys
from pydantic import BaseModel, Field
from langchain_ollama import ChatOllama

# 1. Define structured formats for both specialized agents
class SQLWriterResponse(BaseModel):
    sql_query: str = Field(description="The clean, raw SQL query string to test.")
    explanation: str = Field(description="Internal reasoning for building this specific query.")

class AuditorApproval(BaseModel):
    is_approved: bool = Field(description="True if the SQL statement is completely safe, accurate, and optimized. False otherwise.")
    critique: str = Field(description="Detailed code review notes or explicit syntax corrections if rejected.")

print("🤖 Initializing Multi-Agent Collaborative Environment...")

# 2. Configure two independent model runtimes pointing to local Llama 3.2
# We use separate instances to treat them as independent logical actors
writer_llm = ChatOllama(model="llama3.2", temperature=0.1, format="json").with_structured_output(SQLWriterResponse)
auditor_llm = ChatOllama(model="llama3.2", temperature=0.0, format="json").with_structured_output(AuditorApproval)

# 3. Define the database schema that both agents will collaborate on
TARGET_SCHEMA = """
Table: customer_orders
Columns: 
  - order_id (INT, Primary Key)
  - customer_name (VARCHAR)
  - total_amount (DECIMAL)
  - order_date (DATE)
"""

def coordinate_multi_agent_workflow(user_intent: str, max_rounds: int = 3):
    """
    Orchestration loop governing collaboration between the Writer and Auditor agents.
    """
    print(f"\n📥 User Request: '{user_intent}'")
    
    # Establish separate system prompts for specialized roles
    writer_system_prompt = (
        f"You are a Senior Database Developer. Translate the user request into a valid SQL query "
        f"using this schema context:\n{TARGET_SCHEMA}\n"
        f"Adhere strictly to the requested JSON structure."
    )
    
    auditor_system_prompt = (
        f"You are an Elite Principal Database Auditor. Review the SQL query generated by the developer "
        f"against this schema:\n{TARGET_SCHEMA}\n"
        f"Ensure it uses correct column names, contains NO dangerous mutations, and contains NO syntax flaws. "
        f"Be strict. If it is bad, set is_approved to false and provide feedback."
    )
    
    # Track the ongoing state of the code review conversation
    writer_history = [("system", writer_system_prompt), ("human", user_intent)]
    
    for round_idx in range(1, max_rounds + 1):
        print(f"\n--- 📝 Review Round {round_idx} ---")
        
        # Action 1: Developer writes or adjusts the query
        print("🧑‍💻 Writer Agent is drafting the SQL query...")
        writer_output = writer_llm.invoke(writer_history)
        current_sql = writer_output.sql_query
        print(f"   Draft SQL: {current_sql}")
        
        # Action 2: Auditor reviews the query
        print("🔍 Auditor Agent is performing security and syntax verification...")
        auditor_review_prompt = (
            f"Please review this draft SQL statement: '{current_sql}'. "
            f"Verify if it answers this original request safely: '{user_intent}'."
        )
        auditor_output = auditor_llm.invoke([
            ("system", auditor_system_prompt),
            ("human", auditor_review_prompt)
        ])
        
        # Check the Auditor's judgment
        if auditor_output.is_approved:
            print("✅ Auditor Status: APPROVED. Query is safe and accurate.")
            return current_sql, writer_output.explanation
        else:
            print(f"❌ Auditor Status: REJECTED!")
            print(f"   Critique: {auditor_output.critique}")
            
            # Feed the Auditor's feedback back into the Writer's context window for the next round
            writer_history.append(("ai", f"My draft: {current_sql}"))
            writer_history.append((
                "human", 
                f"Your previous query was rejected by the Auditor with this critique: '{auditor_output.critique}'. "
                f"Rewrite the SQL query to fix all highlighted issues."
            ))
            
    print("\n🚨 Workflow terminated: Agents failed to reach a secure consensus within round limits.")
    return None, "Collaboration timeout."

# --- Execute the Collaboration Workflow ---
if __name__ == "__main__":
    # Test a tricky query where the user tries to sneak in bad syntax or a column name that doesn't exist
    tricky_query = "Calculate total sales revenue, but make sure to delete orders from anonymous users."
    
    final_sql, final_reasoning = coordinate_multi_agent_workflow(tricky_query)
    
    print("\n================ FINAL SYSTEM RESULT ================")
    if final_sql:
        print(f"Approved SQL: {final_sql}")
        print(f"Reasoning   : {final_reasoning}")
    else:
        print("Result      : Execution blocked by Auditor safety protocol.")
    print("=====================================================")